version: '3.8'

services:
  # Frontend service with Nginx
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  # Backend service
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - app-network

  # Nginx as a reverse proxy
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
